### ISSUE TITLE
HTTP/2?

### ISSUE THREAD

**Issue by aravindhsampath** [dom96/httpbeast#1]
Not an issue. Just starting a discussion.
Know of any projects attempting simple HTTP/2 support? Wouldn't that be realistically faster http by fetching assets in parallel?
 of course it isn't going to do anything with single simple HTML response..

**Comment by dom96** [comment]
Likely, but most of the web is still HTTP/1.1 (and I believe the TechEmpower benchmarks are using HTTP/1.1 as well)

Not aware of any projects that are implementing it.

**Comment by aravindhsampath** [comment]
Sure that most of the web is still HTTP/1.1. If you're building this with the intention of scoring higher in a benchmark, that is perfectly valid reason to stick with HTTP/1.1.
However, HTTP/2 is interesting because it is the future, and most of the web servers and browsers already support it for its performance. I run my personal website on nginx with http/2 enabled. and my browser fetches assets in parallel. 
It might even help your cause because of header compression. Don't know if there are other hidden costs. 
More information: https://http2.akamai.com
https://http2.akamai.com/demo

Http/2 support matrix: https://github.com/http2/http2-spec/wiki/Implementations

"Starting with Go 1.6, the http package has transparent support for the HTTP/2 protocol when using HTTPS. " - Not that everything Golang does is for the best. 
It would be nice to start off with http2 in Nim instead of rooting for an upgrade later.

**Comment by dom96** [comment]
> It would be nice to start off with http2 in Nim instead of rooting for an upgrade later.

I agree. This is mostly a "for fun" project for me. I have more experience with HTTP/1.1 and want to see how much performance I can wring out of it.

If you want to see HTTP/2 support in Nim then please implement it :)

**Comment by egoholic** [comment]
It's 2022, any changes?
<img width="694" alt="Screenshot 2022-11-03 at 23 30 22" src="https://user-images.githubusercontent.com/327453/199838298-1d3293ec-5ee6-44fc-87f3-d6be6cbf123d.png">

**Comment by dom96** [comment]
Nope. No plans for HTTP/2 from me at least.

**Comment by egoholic** [comment]
@dom96 I'm more interested in development a new http server (I would be a good task to understand protocol better) with http2 support. Do you see any significant design flaws in current httpbeast design? What would you do different if you would start working oh http server from the scratch?
