### ISSUE TITLE
Add some documentation for HTTPBeast

### ISSUE THREAD

**Issue by andreaferretti** [dom96/httpbeast#15]
So that I can use it as a backend for Rosencrantz :-) I guess the API is mostly compatible with asynchttpserver, since Jester supports both, but I really have no idea

**Comment by dom96** [comment]
Not much more to it than this: https://github.com/dom96/httpbeast/blob/master/tests/helloworld.nim

**Comment by andreaferretti** [comment]
Ok, seems easy. It will only be complicated to handle both asynchttpserver and httpbeast since the `Request` objects are pretty different, but I hope to be able to implement some compatible api.

Just one doubt: I see 

```nim
proc send*(req: Request, code: HttpCode, body: string, headers="") =
  ## Responds with the specified HttpCode and body.
  ##
  ## **Warning:** This can only be called once in the OnRequest callback.
```

For chunked responses I can use `unsafeSend`, right?

**Comment by Stuffe** [comment]
Documentation would be nice (aka make it actually useful). How do you do POST requests?...

**Comment by dom96** [comment]
https://github.com/dom96/httpbeast/blob/master/tests/dispatcher.nim#L16

**Comment by Stuffe** [comment]
How do I set headers/cookies then, that doesn't seem to be in the tests. I think most people who didn't code the whole thing themselves think actual documentation is always the best documentation...

**Comment by dom96** [comment]
Sure, but I'd say you shouldn't be afraid to look into the code, especially for something as low-level as httpbeast. Maybe you'd be better off using Jester?

**Comment by Stuffe** [comment]
So yesterday I also figured out how to use headers and set cookies, by reading the code as you say. But then I ran into not being able to serve static binary files and I went to Jester as you also say. I understand that you do all this for free and I have no right to complain, but you have knowledge that you can probably hash out in 10 minutes that would have saved me and many others in the future 2 hours of figuring things out. 

I want to build a real website (with sessions/cookies/static files/post requests) and the way I came to this project was through a list of names all unknown to me. This project stood out for being fast, so it was the first one I tried. Had I known this was more specific I would have gone to Jester. Just 1 sentence about "This is for X, if you want something general I suggest you check out Jester" could have saved me 2 hours

**Comment by dom96** [comment]
Unfortunately I cannot predict everything and to be fair the httpbeast readme is indeed very barebones.

But sure, I'll add this particular tip to the readme.
