### ISSUE TITLE
Crashes with --gc:boehm

### ISSUE THREAD

**Issue by PMunch** [dom96/httpbeast#24]
When I compiled some code with `--gc:boehm` and `--threads:on` httpbeast threw this crash:
```
Traceback (most recent call last)
httpbeast.nim(287)       eventLoop
httpbeast.nim(166)       processEvents
asyncdispatch.nim(1516)  poll
asyncdispatch.nim(1215)  runOnce
httpbeast.nim(261)       updateDate
times.nim(1078)          now
times.nim(1050)          local
times.nim(853)           inZone
times.nim(830)           zonedTimeFromTime
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by copetol** [comment]
import threadpool
helps me

**Comment by dom96** [comment]
Guessing Nim doesn't support {.threadvar.} on boehm? Maybe this should be a Nim bug?

**Comment by dom96** [comment]
I will close this as I don't have much interest in fixing it myself. I'm also 90% sure it's a Nim bug. So if you want this fixed I'd recommend reporting in the Nim repo (after possibly verifying that it is in fact a Nim bug).
