### ISSUE TITLE
Allow different amount of threads from number of cores

### ISSUE THREAD

**Issue by PMunch** [dom96/httpbeast#25]
Currently when enabling threads it will always spin up the same amount of threads as cores. This should be possible to override with a setting.

**Comment by jasonprogrammer** [comment]
@dom96 Would something like this be acceptable?:

https://github.com/dom96/httpbeast/pull/32

I haven't tested the changes yet; if the changes look good I can do some testing.

**Comment by jasonprogrammer** [comment]
I created this PR:

https://github.com/dom96/jester/pull/250

over in the Jester repository. The PR assumes that a new version of httpbeast has been created, and that a new version of Jester will be created. (I'm not sure how the releases of these two projects work)

**Comment by dom96** [comment]
We've got this as a setting now in HttpBeast.
