### ISSUE TITLE
An error occurred during runtime。Error: undeclared identifier: 'EWOULDBLOCK'

### ISSUE THREAD

**Issue by gxdyxh** [dom96/httpbeast#33]
PS D:\code\nim> nim c -r .\http_test.nim
Hint: used config file 'E:\tool\nim-1.2.0\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: http_test [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: macros [Processing]
Hint: asyncdispatch [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: times [Processing]
Hint: time_t [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: heapqueue [Processing]
Hint: asyncstreams [Processing]
Hint: asyncfutures [Processing]
Hint: deques [Processing]
Hint: cstrutils [Processing]
Hint: monotimes [Processing]
Hint: nativesockets [Processing]
Hint: net [Processing]
Hint: sets [Processing]
Hint: ssl_certs [Processing]
Hint: ospaths [Processing]
Hint: httpbeast [Processing]
Hint: selectors [Processing]
Hint: httpcore [Processing]
Hint: future [Processing]
Hint: underscored_calls [Processing]
Hint: logging [Processing]
Hint: osproc [Processing]
Hint: strtabs [Processing]
Hint: streams [Processing]
Hint: cpuinfo [Processing]
Hint: parser [Processing]
C:\Users\gqz\.nimble\pkgs\httpbeast-0.2.2\httpbeast.nim(183, 36) Error: undeclared identifier: 'EWOULDBLOCK'

**Comment by dom96** [comment]
From readme:

> Note: This HTTP server does not support Windows.
