### ISSUE TITLE
Using asynctool / master

### ISSUE THREAD

**Issue by waghanza** [dom96/httpbeast#34]
Hi @dom96,

I think https://github.com/dom96/httpbeast/blob/f352aace35c47edc71dec370a389108560804c79/httpbeast.nimble#L15 is not needed anymore (I mean using a **git ref**)

The branch has been merged https://github.com/cheatfate/asynctools/commit/c478bb74268c65e7400e81f49d26f82d20f1f57a

Regards,

**Comment by dom96** [comment]
This has been resolved.
