### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xflywind** [dom96/httpbeast#37]
Hi @dom96 , which license this library chooses? There is no license in this repo. I want to add windows support for `httpbeast`. I have finished a fragile prototype [ioselectors](https://github.com/xflywind/ioselectors) enhancements for windows. It seems not too hard to add windows support(Though I don't know its performance, considering that `wepoll` uses IOCP, maybe it is not too bad.).

I have tested `httpbeast` in windows, helloworld seems to work(use `wepoll`).
![image](https://user-images.githubusercontent.com/43030857/89272723-23e3c680-d671-11ea-9b28-ce5a4f01d840.png)

Simple benchmark in windows using `jmeter`:

asynchttpserver (400 threads + 1s) and the throughput is 13388/s

httpbeast (600 threads + 1s) and the throughput is 22486/s

![image](https://user-images.githubusercontent.com/43030857/89420917-f88ed380-d765-11ea-95c3-12c544eebdea.png)

**Comment by xflywind** [comment]
Any news?

**Comment by dom96** [comment]
Sorry for the delay, done in https://github.com/dom96/httpbeast/commit/f1a57c63fc1d2b6a9cd53f09aa3b7d0d081a4ced.

I have designed httpbeast to be POSIX-only from the outset. An implementation that is aimed at Windows should use IOCP and should be a separate project.

**Comment by xflywind** [comment]
Thanks!
