### ISSUE TITLE
Running a simple example based on the `httpbeast 0.2.2` framework made an error.

### ISSUE THREAD

**Issue by lihf8515** [dom96/httpbeast#41]
Running a simple example based on the `httpbeast 0.2.2` framework made an error :`getData.headersFinished` Selector not ready to send.[AssertionDefect].

Note: When i use browser request, there is no error, but when i use wrk -c100-d20--latency http://192.12.1.1:8080/ for stress test, there is an error.

My code is as follows:

```nim
import segfaults
import random

import options, asyncdispatch

import httpbeast

proc onRequest(req: Request): Future[void] {.async.} =
  if req.httpMethod == some(HttpGet):
    case req.path.get()
    of "/":
      randomize()
      let t = rand(999)
      await sleepAsync(t)
      req.send("Hello World")
    else:
      req.send(Http404)

run(onRequest)
```

The errors I have obtained are as follows:
```
Starting 6 threads
Listening on port 8080
/home/lhf/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(287) eventLoop
/home/lhf/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(166) processEvents
/home/lhf/Nim-devel/lib/pure/asyncdispatch.nim(1626) poll
/home/lhf/Nim-devel/lib/pure/asyncdispatch.nim(1367) runOnce
/home/lhf/Nim-devel/lib/pure/asyncdispatch.nim(208) processPendingCallbacks
/home/lhf/Nim-devel/lib/pure/asyncmacro.nim(22) onRequestNimAsyncContinue
/home/lhf/桌面/t.nim(15) onRequestIter
/home/lhf/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(342) send
/home/lhf/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(321) send
/home/lhf/Nim-devel/lib/system/assertions.nim(30) failedAssertImpl
/home/lhf/Nim-devel/lib/system/assertions.nim(23) raiseAssert
/home/lhf/Nim-devel/lib/system/fatal.nim(49) sysFatal
[[reraised from:
/home/lhf/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(287) eventLoop
/home/lhf/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(166) processEvents
/home/lhf/Nim-devel/lib/pure/asyncdispatch.nim(1626) poll
/home/lhf/Nim-devel/lib/pure/asyncdispatch.nim(1367) runOnce
/home/lhf/Nim-devel/lib/pure/asyncdispatch.nim(208) processPendingCallbacks
/home/lhf/Nim-devel/lib/pure/asyncfutures.nim(281) :anonymous
/home/lhf/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(223) :anonymous
/home/lhf/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(94) onRequestFutureComplete
]]
Error: unhandled exception: /home/lhf/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(321, 10) `getData.headersFinished` Selector not ready to send. [AssertionDefect]
```

**Comment by dom96** [comment]
Hm, seems like there may be some weird interactions between the async loop and httpbeast when it comes to this benchmark. Does it also happen with https://github.com/dom96/httpbeast/blob/master/tests/benchmark.nim ?

**Comment by lihf8515** [comment]
Your benchmark code does not have this problem. This is because this code responds immediately after receiving the request. But my code is to simulate the real environment, for example: asynchronous access to the database, it will have a slight delay before responding.
In the real environment, after I added the code for asynchronous operation of the database, this error also appeared, and the result was the same as the simulation using `sleepAsync()`.

**Comment by lihf8515** [comment]
Use the compiler option `-d:usestd` or do not use `--threads:on`, so that this error will not occur when only single-threaded asynchronous is used. But this will not play the role of multi-core CPU, performance will be affected.

**Comment by lihf8515** [comment]
I found that when I remove the ʻassert` statement in the `proc send*(req: Request, code: HttpCode, body: string, headers="")` function, the stress test is normal and no error occurs. .

**Comment by lihf8515** [comment]
I found that when I remove the assert statement in the proc send*(req: Request, code: HttpCode, body: string, headers="") function, the stress test is normal and no error occurs.

**Comment by dom96** [comment]
> Your benchmark code does not have this problem. This is because this code responds immediately after receiving the request. But my code is to simulate the real environment, for example: asynchronous access to the database, it will have a slight delay before responding.

Yes, I understand. I just wanted to rule out that everything got broken by some new Nim changes :)

This is definitely a bug.

**Comment by dom96** [comment]
> I found that when I remove the assert statement in the proc send*(req: Request, code: HttpCode, body: string, headers="") function, the stress test is normal and no error occurs.

If it's an ``assert`` then the compiler will remove it when compiled with ``-d:release``. You don't have to remove it manually then, just compile with ``-d:release`` or ``-d:danger`` (which you should be doing anyway for benchmarks).

**Comment by lihf8515** [comment]
I tried, use `- d：release` parameter is not good, must use `- d：danger` or use `--assertions:off`.

**Comment by xflywind** [comment]
@lihf8515 It should be fixed by https://github.com/dom96/httpbeast/pull/73

**Comment by dom96** [comment]
Yeah, this is the same bug.
