### ISSUE TITLE
A way to kill HTTP beast? 

### ISSUE THREAD

**Issue by ohPaco** [dom96/httpbeast#72]
Is there a way to kill HTTP beast out of a running process?

**Comment by dom96** [comment]
Don't think so. What's your high-level goal?

**Comment by ohPaco** [comment]
> Don't think so. What's your high-level goal?
I fork my nim process , and id like the child process to ideally run independently from jester and http beast as to not be running these processes 2x

**Comment by dom96** [comment]
Feel free to reopen if you're still interested in this.
