### ISSUE TITLE
httpbeast-0.4.1/httpbeast.nim(373, 17) Error: undeclared identifier: 'addTimer'

### ISSUE THREAD

**Issue by tomasky** [dom96/httpbeast#76]
nimlang version:1.6.6 , 32bit linux

**Comment by dom96** [comment]
compile:

```nim
import selectors
echo(

```

**Comment by tomasky** [comment]
yes ,
--os:android
--cpu:arm
so ,the proc  not support android?

**Comment by tomasky** [comment]
yes ,
--os:android
--cpu:arm
so ,the proc  not support android?

**Comment by dom96** [comment]
it possibly is, could be a great patch for the Nim stdlib
